name: iiit_skeleton
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  native_pdf_view: ^4.0.1
  percent_indicator: "^2.1.7+2"
  flutter:
    sdk: flutter
  carousel_slider: ^3.0.0
  flutter_svg: ^0.22.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/iiit_sonepat_syllabus.pdf
   - images/
   - images/1.png
   - images/2.png
   - images/4.png
   - images/6.png
   - images/8.jpg
   - images/9.jpg
   - images/10.png
   - images/11.png
   - images/Login_Page/logo.png
   - images/Login_Page/IIIT Sonepat Logo.png
   - images/Login_Page/google.png


  fonts:
    - family: MonoLisa
      fonts:
        - asset: fonts/MonoLisa-Regular.ttf
    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

